# .github/workflows/python_tests.yml

name: Python CI/CD Tests

on:
  push:
    branches: [ main ] # This workflow runs when code is pushed to the 'main' branch
  pull_request:
    branches: [ main ] # This workflow also runs when a pull request targets 'main'

jobs:
  build:
    runs-on: ubuntu-latest # The type of virtual machine to run the job on (e.g., Ubuntu Linux)

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Action to get your repository's code

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use any Python 3 version available

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Installs Pillow and pytest from your requirements.txt

    - name: Run tests with pytest
      run: |
        pytest tests/ # Runs pytest on all files in the 'tests/' directory